INSERT INTO t_p72465170_avito_like_board.settings (key, value) VALUES
('ads_per_page', '10'),
('ads_per_page_search', '10'),
('max_search_results', '0'),
('min_search_chars', '4'),
('quick_search_limit', '5'),
('related_ads_count', '5'),
('related_same_category_only', 'true'),
('popular_ads_count', '5'),
('tag_cloud_limit', '20'),
('max_pending_ads', '0'),
('new_ad_hours', '24'),
('updated_ad_hours', '24'),
('category_separator', '»'),
('tag_separator', '/'),
('speedbar_separator', '»'),
('ad_date_format', 'j-m-Y, H:i'),
('ad_sort_by', 'date'),
('ad_sort_order', 'desc'),
('catalog_sort_by', 'date'),
('catalog_sort_order', 'desc'),
('indexnow_enabled', 'false'),
('indexnow_provider', 'indexnow'),
('decline_dates', 'false'),
('auto_generate_meta', 'false'),
('notify_new_ads', 'false'),
('allow_user_tags', 'true'),
('warn_concurrent_edit', 'true'),
('rating_type', 'stars')
ON CONFLICT (key) DO NOTHING;