ALTER TABLE t_p72465170_avito_like_board.user_groups
  ADD COLUMN IF NOT EXISTS short_name VARCHAR(20),
  ADD COLUMN IF NOT EXISTS account_deletion_policy SMALLINT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS can_view_offline BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_temporary BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS can_access_admin BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS can_edit_all_news BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;