ALTER TABLE t_p72465170_avito_like_board.users
  ADD COLUMN IF NOT EXISTS group_id INTEGER,
  ADD COLUMN IF NOT EXISTS is_banned BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS can_post BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS can_comment BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS last_visit TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS group_expire_date TIMESTAMP WITH TIME ZONE;